import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import { CartProvider } from '@/features/cart/context/CartContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="pt-BR" data-theme="light">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <CartProvider>
        <Header />
        {children}
        <Footer />
      </CartProvider>
    </body>
  </html>
);

export default RootLayout;
